### ISSUE TITLE
Nothing was implemented.

### ISSUE THREAD

**Issue by monacofj** [so-ii-2019/sh19-oleoshell#1]

**Comment by RobertaBrandao** [comment]
Boa tarde, professor! Tudo bem?

No git do nosso trabalho de SO2 recebemos um Issue como Não implementado
mas implementamos o projeto (mesmo que não completamente) e enviamos, é
nosso segundo release:
https://github.com/so-ii-2019/sh19-oleoshell/releases/tag/shell-r2

Será que tivemos algum problema enviando para o git? O senhor poderia nos
ajudar entender o que houve?

Atenciosamente,
Roberta B.

Em dom, 21 de jul de 2019 às 15:27, Monaco F. J. <notifications@github.com>
escreveu:

**Comment by monacofj** [comment]
It was in another release tag. Ok.
